### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by madelynnblue** [coreos/go-quay#1]
I would recommend using more conventional Go names for this API. See the [youtube](https://godoc.org/google.golang.org/api/youtube/v3) API, for example. You start it with:

```
youtubeService, err := youtube.New(oauthHttpClient)
```

I'd like to see (where `client` can be nil and is of type *http.Client, just like the youtube package):

```
quayService, err := quay.New(client)
```

I'm aware you just changed the package name, but this is how I prefer to see APIs implemented in Go. See also the [drive](https://godoc.org/code.google.com/p/google-api-go-client/drive/v2) API, which uses the same pattern.

**Comment by chancez** [comment]
Internally I asked if anyone had naming suggestions but go no responses. Yeah I could definitely rename the package to "quay" and you would have `quay.New()` as the facade client.

**Comment by chancez** [comment]
@mjibson Any preferences on what the facade client's type name should be?

Currently it's `QuayAPI` because go-swagger uses the "info.title"  from the schema to infer a default name, and I didn't like "QuayFrontend" (what it got from the schema).

If I renamed the package to `quay` and the client type to `client` we could have `quayClient, err := quay.New()` which returns a type `quay.Client`.

@josephschorr @jakedt perhaps you guys have opinions on this as well?

**Comment by josephschorr** [comment]
+1 to just `quay`. I can also change the name in the swagger spec, if you like.
